### ISSUE TITLE
Custom Infusing Crafting

### ISSUE THREAD

**Issue by CoolerProRB** [blakesmods/web#5]
I trying to add a soul jar chicken as recipe but it say doesnt exist, how do i fix it.
InfusionCrafting.addRecipe("warden_spawn_egg", <item:minecraft:warden_spawn_egg> * 1, //Output
    [
        <item:minecraft:egg>, //Middle Item
        <item:mysticalagradditions:insanium_essence>, 
        <item:mysticalagriculture:chicken>, 
        <item:mysticalagradditions:insanium_essence>, 
        <item:kubejs:warden_fragment>, 
        <item:mysticalagradditions:insanium_essence>, 
        <item:kubejs:warden_fragment>, 
        <item:mysticalagradditions:insanium_essence>, 
        <item:kubejs:warden_fragment>
    ]
);

**Comment by BlakeBr0** [comment]
Your items seem to be missing the <> on each side, ex `<item:mysticalagradditions:insanium_essence>`. Also I'm not sure if you're using imports (if that even works for this, haven't tested) but it should be mods.mysticalagriculture.InfusionCrafting.addRecipe().

**Comment by CoolerProRB** [comment]
i have <> on each side but github didnt show it, I also imported, the problem is when i trying to use soul jar such as `<item:mysticalagriculture:chicken>` it will say item does not exist, i tried for every soul jar.

**Comment by BlakeBr0** [comment]
I'm not sure I understand what you're trying to do. Can you put the script that's not working? Also there isn't an item with that id. If you want to use a soul jar you can `/ct hand` one of the filled jars to get the proper item string. The mob type is specified with NBT.

**Comment by CoolerProRB** [comment]
its work! Thank you for your help!

**Comment by BlakeBr0** [comment]
Sweet 👍
